Switch Sonar job to use Java 11
adorsys/xs2a-adapter pull request #544
Opened 2020-12-04 15:39 UTC by DG0lden

2020-12-04 16:13 UTC, tnein requested changes
As you can see [here](https://github.com/actions/setup-java), the major version syntax is preferred (if not the only working way for JDK11). So I would suggest to use the following:

```
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
```

2020-12-07 09:47 UTC, berezkin88 commented
I didn't found that major version syntax is marked as "preferred" anywhere. Browsing across the net, I see both options `1.11` and `11` are equally valid.

2020-12-07 09:47 UTC, berezkin88 approved these changes

2020-12-07 19:06 UTC, tnein approved these changes

2020-12-08 08:26 UTC, DG0lden commented
@berezkin88 pls merge according to your rules to assure proper sync GitLab->GitHub

2020-12-08 08:36 UTC, merged